<program> ::= <declaration> "\n" <program> | <declaration> | ""

<declaration> ::= <assignment-declaration> | <expression-declaration>

<assignment-declaration> ::= "let" <identifier> "=" <expression>
<expression-declaration> ::= <expression>

<expression> ::= <binary-expression>

<binary-expression> ::= <unary-expression> <binary-operator> <binary-expression>
                      | <unary-expression>
<binary-operator>   ::= "+" | "-" | "*" | "/" | "**" | "%"
                      | "==" | "!=" | ">" | ">=" | "<" | "<="
                      | "and" | "or"

<unary-expression>  ::= <unary-operator> <value> | <value>
<unary-operator>    ::= "-" | "not"

<value>                    ::= <parenthesized-expression> | <literal> | <identifier>
<parenthesized-expression> ::= "(" <expression> ")"
<literal>                  ::= <number> | "true" | "false"
